/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVitalsRouteImport } from './routes/_app.vitals'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppQueueRouteImport } from './routes/_app.queue'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConsultationRouteImport } from './routes/_app.consultation'
import { Route as AppCampsRouteImport } from './routes/_app.camps'
import { Route as AppPatientsIndexRouteImport } from './routes/_app.patients.index'
import { Route as AppPatientsNewRouteImport } from './routes/_app.patients.new'
import { Route as AppPatientsIdRouteImport } from './routes/_app.patients.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVitalsRoute = AppVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationRoute = AppConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => AppRoute,
} as any)
const AppCampsRoute = AppCampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsNewRoute = AppPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIdRoute = AppPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camps': typeof AppCampsRoute
  '/consultation': typeof AppConsultationRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/inventory': typeof AppInventoryRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/queue': typeof AppQueueRoute
  '/reports': typeof AppReportsRoute
  '/vitals': typeof AppVitalsRoute
  '/patients/$id': typeof AppPatientsIdRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/patients/': typeof AppPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camps': typeof AppCampsRoute
  '/consultation': typeof AppConsultationRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/inventory': typeof AppInventoryRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/queue': typeof AppQueueRoute
  '/reports': typeof AppReportsRoute
  '/vitals': typeof AppVitalsRoute
  '/patients/$id': typeof AppPatientsIdRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/patients': typeof AppPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/camps': typeof AppCampsRoute
  '/_app/consultation': typeof AppConsultationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/pharmacy': typeof AppPharmacyRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/vitals': typeof AppVitalsRoute
  '/_app/patients/$id': typeof AppPatientsIdRoute
  '/_app/patients/new': typeof AppPatientsNewRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camps'
    | '/consultation'
    | '/dashboard'
    | '/feedback'
    | '/inventory'
    | '/pharmacy'
    | '/queue'
    | '/reports'
    | '/vitals'
    | '/patients/$id'
    | '/patients/new'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camps'
    | '/consultation'
    | '/dashboard'
    | '/feedback'
    | '/inventory'
    | '/pharmacy'
    | '/queue'
    | '/reports'
    | '/vitals'
    | '/patients/$id'
    | '/patients/new'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/camps'
    | '/_app/consultation'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/inventory'
    | '/_app/pharmacy'
    | '/_app/queue'
    | '/_app/reports'
    | '/_app/vitals'
    | '/_app/patients/$id'
    | '/_app/patients/new'
    | '/_app/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vitals': {
      id: '/_app/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AppVitalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultation': {
      id: '/_app/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof AppConsultationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/camps': {
      id: '/_app/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof AppCampsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/new': {
      id: '/_app/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AppPatientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$id': {
      id: '/_app/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AppPatientsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCampsRoute: typeof AppCampsRoute
  AppConsultationRoute: typeof AppConsultationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
  AppQueueRoute: typeof AppQueueRoute
  AppReportsRoute: typeof AppReportsRoute
  AppVitalsRoute: typeof AppVitalsRoute
  AppPatientsIdRoute: typeof AppPatientsIdRoute
  AppPatientsNewRoute: typeof AppPatientsNewRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampsRoute: AppCampsRoute,
  AppConsultationRoute: AppConsultationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPharmacyRoute: AppPharmacyRoute,
  AppQueueRoute: AppQueueRoute,
  AppReportsRoute: AppReportsRoute,
  AppVitalsRoute: AppVitalsRoute,
  AppPatientsIdRoute: AppPatientsIdRoute,
  AppPatientsNewRoute: AppPatientsNewRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
